### ISSUE TITLE
cannot install using pip

### ISSUE THREAD

**Issue by Arghya999** [haranrk/DigiPathAI#11]
I tried installing using pip install DigiPathAI or pip install DigiPathAI==0.1.3

but got the below error :- 

ERROR: Could not find a version that satisfies the requirement DigiPathAI (from versions: none)
ERROR: No matching distribution found for DigiPathAI

also the verbose i got from pip install DigiPathAI -vvv : -

Created temporary directory: /tmp/pip-ephem-wheel-cache-tl8zisak
Created temporary directory: /tmp/pip-req-tracker-wn0ph20o
Created requirements tracker '/tmp/pip-req-tracker-wn0ph20o'
Created temporary directory: /tmp/pip-install-ve44mpso
1 location(s) to search for versions of DigiPathAI:
* https://pypi.org/simple/digipathai/
Getting page https://pypi.org/simple/digipathai/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/digipathai/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/digipathai/ HTTP/1.1" 304 0
Analyzing links from page https://pypi.org/simple/digipathai/
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/92/51/96e7753dbfd966d5cd5c1608895361b82a0518a16178caff9c3c31610964/DigiPathAI-0.0.2-py3.5.egg#sha256=a1cca7970ffa63e2d2824510dec955ea17dfdad157c67bdb23f99e750110d5c5 (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/15/ad/b5f5ac44e189cc9e0f2ba376ff7c3a10cf022c828a8f6a8d684245414621/DigiPathAI-0.0.3-py3.5.egg#sha256=c94bdaddbeb38b7c3a1781ec17f78b71e34fa4c934917e77ce78ee94d1e8b2aa (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/f9/de/06eb8f98c94c573597ba111082b4824192a8fe7524d41a50fa700d7e44f9/DigiPathAI-0.0.4-py3.5.egg#sha256=d6188935e2895f68faa8bc906040d72337512cb006bd355d1b68309b5157c2f6 (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/1b/fb/f55c0ef3bc1960ca5d9c07189ba5fa282f990150d4f367a6c9c7592669ea/DigiPathAI-0.0.6-py3.5.egg#sha256=4aea007c6be1f181e92dd9d4ddf53254b4c463e75cd35b223ff54f1b39dcf7e9 (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/e6/b5/8cfcb3d134ecc82d363cd3cba79ed8db0dfbb0bd5ce0fb09ade5bda68e3f/DigiPathAI-0.0.7-py3.5.egg#sha256=7c0e8258d970249cc8e4b3a0e269520727b9e949687683833158c318a0bf1f1a (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/7d/94/ec4c2022462ab194288674a4ae36ae0c1269c199bd9c2197082efdb16bf9/DigiPathAI-0.0.8-py3.5.egg#sha256=4c95d7ca2800cd720553ea2081943f5bed2d798904629f7ead2542ef06054c88 (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/0a/bb/01d0c4f651af6c42a22b83ef2325bc97fd0908860bba2e4845de9a3652f6/DigiPathAI-0.0.9-py3.5.egg#sha256=03110c58ef79aa6e93f6f5770020f0ff1da94d371c01d1348c50a5af4ede7b5e (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/85/5c/6b281275f050cf0062da9435f82bfce5f617756dab0483dcaec9fedca75b/DigiPathAI-0.1.0-py3.5.egg#sha256=d59b60e97a9f39533304ecbc76f3d23b77ec475a21f6c17079bfae6291b33fc6 (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/75/f4/e1e1930c244ce23e5a39a35d91860cd2a59af449639b9592d96fc6e19afd/DigiPathAI-0.1.1-py3.5.egg#sha256=3e0d675e9127089d4f367d2bbe6eacc41bcdac7b7d50df223b3b894e9e959945 (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/23/cb/2480e7e5d1f2b904f60246e752acff1d0e2e2478eee32f4b2ade27216e8c/DigiPathAI-0.1.2-py3.5.egg#sha256=a4b0ac296e59f6d69f5e36973e973ebc023d333ef7e580e47257a8ec51746d85 (from https://pypi.org/simple/digipathai/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/a7/7a/bd9201b2249c8d108a3137c6a2aee1f055e68426af8446afe9d5b6a43692/DigiPathAI-0.1.3-py3.5.egg#sha256=61e72646062d2724563a6bd29d33195eff9a5acd4fcd6cb17e1d0de5d22e42ef (from https://pypi.org/simple/digipathai/)
Given no hashes to check 0 links for project 'DigiPathAI': discarding no candidates
ERROR: Could not find a version that satisfies the requirement DigiPathAI (from versions: none)
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-wn0ph20o'
ERROR: No matching distribution found for DigiPathAI
Exception information:
Traceback (most recent call last):
  File "/home/aicoe/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/home/aicoe/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/home/aicoe/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/aicoe/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/aicoe/anaconda3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 311, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, self.require_hashes)
  File "/home/aicoe/anaconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 225, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/aicoe/anaconda3/lib/python3.7/site-packages/pip/_internal/index.py", line 906, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for DigiPathAI

**Comment by Arghya999** [comment]
I feel the pip installation fro pypi fails due to the unavailability of a .wheel file.
I was able to install it fro the git link  using :- pip install "git+https://github.com/haranrk/DigiPathAI"

**Comment by haranrk** [comment]
That indeed was a weird error. Nevertheles, I uploaded the latest version to PyPI now. If the problem persists, let me know.
